name: MSBuild

on: push

jobs:
  first_job:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Display hello world
        run: echo "hello world pwsh"
        shell: pwsh

      - name: run ps1File
        run: powershell -NoProfile -ExecutionPolicy Unrestricted ./helloworld.ps1
        shell: cmd